### PR TITLE
workflows: use GH-CLI to checkout and push to PR

### PR DESCRIPTION
**Pull request by l-zeuch**
This commit modifies the generate.yml workflow to use the pre-installed
GitHub CLI which comes on all GitHub-hosted runners. It is used to
properly checkout the pull request, which then allows us to actually
push automagic regeneration of completion sources.

**Terms**
- [x] I agree to follow this project's [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I have read and understood this project's [Contributing Guidelines](../CONTRIBUTING.md)

### CODE REVIEW

**Comment by l-zeuch** [comment]
Draft for now because I still need to actually test this workflow, but in theory it should work.

**Comment by l-zeuch** [comment]
After a lot of madness and fixups, it finally works!
image

**Review by LRitzdorf — APPROVED** [review]
Some step names don't use consistent letter cases, but that's fine :grin:

**Comment by l-zeuch** [comment]
I'll fix that, commit follows. :+1:

**Comment by l-zeuch** [comment]
There we go, ready for merge!

**Pull request merged**
