### PR TITLE
all: flatten project project tree structure

### PR DESCRIPTION
**Pull request by l-zeuch**
This commit flattens the repository's tree a little bit, by moving documentation
into appropriate folders: CONTRIBUTING.md is for github purposes, thus it fits
better in .github/; the written exchange is documentation, hence moved to doc/.

Signed-off-by: Luca Zeuch <l-zeuch@email.de>

**Terms**
- [x] I agree to follow this project's [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I have read and understood this project's [Contributing Guidelines](../CONTRIBUTING.md)

----

I'm not sure whether this is actually needed -- I just prefer a less cluttered repository root; I'll leave you to decide whether to merge it or not.

### CODE REVIEW

**Comment by l-zeuch** [comment]
I'm fairly certain we can move the `Makefile` into the `scripts/` folder as well; let me know what you think.

**Review by LRitzdorf — COMMENTED** [review]
This is all right, but do we really want to move `CONTRIBUTING.md`? It does traditionally go in the project root, so it's immediately visible when cloning the repo.

**Comment by l-zeuch** [comment]
I've seen many different iterations of a location for `CONTRIBUTING.md`; GitHub documents it as follows:
> To help your project contributors do good work, you can add a file with contribution guidelines to your project repository's root, docs, or .github folder. When someone opens a pull request or creates an issue, they will see a link to that file. The link to the contributing guidelines also appears on your repository's contribute page.

<https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors>

----
Seeing as GitHub links it either way, I'd say it doesn't quite matter; plus, it is referenced in the `README.md` anyway.

**Review by LRitzdorf — APPROVED** [review]
Ah, that's fair, then. Sounds good to me!

**Pull request merged**
